version: "3.3"
services:
  postgres:
    container_name: cos40005_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # Note: This only creates ONE database on startup (SwinCMS). 
      # See note below for the n8n database
      POSTGRES_DB: SwinCMS
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432" 
    networks:
      - postgres
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: cos40005_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - POSTGRES_DB=SwinCMS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=cos40005_postgres
      - POSTGRES_PORT=5432
    networks:
      - postgres
    depends_on:
      - postgres

  redis:
    container_name: cos40005_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: cos40005_pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_DATA_DIR: "'/var/lib/pgadmin'"
      PGADMIN_CONFIG_LOG_FILE: "'/var/lib/pgadmin/pgadmin4.log'"
    user: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

  n8n:
    image: docker.io/n8nio/n8n:latest
    container_name: cos40005_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=cos40005_n8n
      - N8N_PORT=5678
      
      # --- NGROK / OAUTH UPDATES ---
      # This tells n8n to use the ngrok domain for webhooks and OAuth callbacks
      - WEBHOOK_URL=https://conditionally-brimful-exie.ngrok-free.dev
      - N8N_EDITOR_BASE_URL=https://conditionally-brimful-exie.ngrok-free.dev
      
      # --- DATABASE CONFIG ---docker compose up -d
      - DB_TYPE=postgres
      - DB_POSTGRE_HOST=cos40005_postgres
      - DB_POSTGRE_USER=postgres
      - DB_POSTGRE_PASSWORD=password
      - DB_POSTGRE_DATABASE=n8n
      - NODE_ENV=development
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - postgres
    depends_on:
      - postgres
      - backend # n8n also needs to wait on backend
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin_data:
  n8n_data: